package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"html/template"
	"io/ioutil"
	"net/http"
	"strconv"

	_ "github.com/lib/pq"
)

var tpl *template.Template
var db *sql.DB
var err error

type Pokemon struct {
	uid       string
	pokedexID int
	owner     string
	name      string
	level     int
}

type user struct {
	username string
	password []byte
}

func init() {
	tpl = template.Must(template.ParseGlob("templates/*.gohtml"))
	postgreConnString, err := ioutil.ReadFile("postgreConnString")
	if err != nil {
		panic(err)
	}
	db, err = sql.Open("postgres", string(postgreConnString))
	if err != nil {
		panic(err)
	}
	fmt.Println("You connected to your database.")
}

func main() {
	http.HandleFunc("/pokefarm/create", create)
	http.HandleFunc("/pokefarm/read", read)
	http.HandleFunc("/pokefarm/update", update)
	http.HandleFunc("/pokefarm/delete", delete)
	http.HandleFunc("/pokefarm", pokefarm)
	http.HandleFunc("/login", login)
	http.HandleFunc("/logout", logout)
	http.HandleFunc("/signup", signup)
	http.HandleFunc("/", index)
	http.ListenAndServeTLS(":10443", "cert.pem", "key.pem", nil)
}

func index(res http.ResponseWriter, req *http.Request) {
	// if LoggedIn, redirects to My Pokedex, if not request to log in and offer sign up button
	if alreadyLoggedIn(req) {
		http.Redirect(res, req, "/pokefarm", http.StatusSeeOther)
		return
	}
	tpl.ExecuteTemplate(res, "index.gohtml", nil)
}

func create(res http.ResponseWriter, req *http.Request) {
	if req.Method != "POST" {
		tpl.ExecuteTemplate(res, "create.gohtml", nil)
		return
	}

	ID_int, ID_interr := strconv.Atoi(req.FormValue("ID"))
	owner := req.FormValue("username")
	name := req.FormValue("name")

	new_pkmn := Pokemon{
		uid:       "", // we dont need it because that will be generated by postgresql
		pokedexID: ID_int,
		owner:     owner,
		name:      name,
		level:     1,
	}

	// validate form values
	if ID_interr != nil {
		http.Error(res, http.StatusText(400), http.StatusBadRequest)
		return
	}

	q := `
		INSERT INTO POKEMONS(pokedexID, owner, name, level)
		VALUES($1, $2, $3, $4);
		`
	_, err = db.Exec(q, new_pkmn.pokedexID, new_pkmn.owner, new_pkmn.name, new_pkmn.level)
	if err != nil {
		http.Error(res, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		res.Write([]byte(err.Error()))
		return
	} else {
		res.Write([]byte("New pokemon added to your PokeFarm."))
		res.Write([]byte(fmt.Sprintf("ID: %d", new_pkmn.pokedexID, new_pkmn.owner, new_pkmn.name, new_pkmn.level)))
	}

}

func read(res http.ResponseWriter, req *http.Request) {
	if req.Method != "GET" {
		http.Error(res, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
		return
	}

	pkmn := Pokemon{}
	row := db.QueryRow("SELECT * FROM pokemons WHERE uid = $1", req.FormValue("uid"))
	err = row.Scan(&pkmn.uid, &pkmn.pokedexID, &pkmn.owner, &pkmn.name, &pkmn.level)
	if err != nil {
		http.Error(res, http.StatusText(500), 500)
	}
	res.Header().Set("Content-Type", "application/json")
	err = json.NewEncoder(res).Encode(pkmn)
	if err != nil {
		http.Error(res, http.StatusText(500), 500)
	}
}

func update(res http.ResponseWriter, req *http.Request) {
	if req.Method != "POST" {
		tpl.ExecuteTemplate(res, "update.gohtml", nil)
		return
	}

	uid := req.FormValue("uid")
	pokedexID, errPID := strconv.Atoi(req.FormValue("pokedexID"))
	owner := req.FormValue("owner")
	name := req.FormValue("name")
	level, errLVL := strconv.Atoi(req.FormValue("level"))

	// validate form values
	if uid == "" || errPID != nil || owner == "" || name == "" || errLVL != nil {
		http.Error(res, http.StatusText(400), http.StatusBadRequest)
		return
	}

	q := `
		UPDATE pokemons SET pokedexID=$1, owner=$2, name=$3, level=$4 WHERE uid=$5;
		`
	result, err := db.Exec(q, pokedexID, owner, name, level, uid)
	if err != nil {
		panic(err)
	}
	rows, err := result.RowsAffected()
	if err != nil {
		panic(err)
	} else if rows > 0 {
		res.Write([]byte("Pokemon updated successfully."))
		fmt.Println("redirected to /pokefarm")
		http.Redirect(res, req, "/pokefarm", http.StatusSeeOther)
	} else {
		res.Write([]byte("No rows were affected."))
	}
	return

}

func delete(res http.ResponseWriter, req *http.Request) {
	if req.Method != "POST" {
		tpl.ExecuteTemplate(res, "delete.gohtml", nil)
		return
	}

	idToDelete := req.FormValue("uid")
	q := `
		DELETE FROM pokemons
		WHERE uid = $1;
	`
	result, err := db.Exec(q, idToDelete)
	if err != nil {
		panic(err)
	}
	rows, err := result.RowsAffected()
	if err != nil {
		panic(err)
	} else if rows > 0 {
		http.Redirect(res, req, "/pokefarm", http.StatusSeeOther)
	} else {
		res.Write([]byte("No rows were affected. Id doesn't exist."))
	}
	return

}
func pokefarm(res http.ResponseWriter, req *http.Request) {
	if alreadyLoggedIn(req) {
		cookie, _ := req.Cookie("session")
		row := db.QueryRow("SELECT USERNAME FROM SESSIONS WHERE SID = $1", cookie.Value)
		currUser := ""
		err = row.Scan(&currUser)
		if err != nil {
			http.Error(res, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
			fmt.Println("query 1")
			return
		}

		q := `
		SELECT * FROM POKEMONS
		WHERE OWNER = $1
		ORDER BY POKEDEXID;
		`
		rows, err := db.Query(q, currUser)
		if err != nil {
			http.Error(res, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
			fmt.Println("query 2")
			return
		}
		defer rows.Close()
		pkmns := make([]Pokemon, 0)
		for rows.Next() {
			pkmn := Pokemon{}
			err := rows.Scan(&pkmn.uid, &pkmn.pokedexID, &pkmn.owner, &pkmn.name, &pkmn.level)
			if err != nil {
				panic(err)
			}
			pkmns = append(pkmns, pkmn)
		}
		if err = rows.Err(); err != nil {
			panic(err)
		}
		tpl.ExecuteTemplate(res, "pokefarm.gohtml", pkmns)
	} else {
		http.Redirect(res, req, "/", http.StatusSeeOther)
		return
	}

}
